### PR TITLE
draw image with block buffer

### PR DESCRIPTION
**Pull request by Qingwu-Li**
export draw_rgb_pixel function to make it capability to draw an image, 
but draw an image pixel by pixel is very slow, introduce draw_x24_pixels function to draw a rectangle
with a block buffer provided by the caller.

### CODE REVIEW

**Comment by tomba** [comment]
Hi! What's your use case?

In the second commit you add a function which basically does a memcpy. If so, is the first one needed at all?

In any case, I think it's probably better to just give python direct access to the buffer, rather than wrapping a memcpy. Something like this could be added to the Framebuffer wrapping:

```
.def("map", [](Framebuffer& self, uint32_t plane) {
	const auto& format_info = get_pixel_format_info(self.format());

	if (plane >= format_info.num_planes)
		throw runtime_error("bad plane");

	auto shape = { self.height(), self.width() * format_info.planes[plane].bitspp / 8 };
	auto strides = { self.stride(plane), sizeof(uint8_t) };

	return py::memoryview::from_buffer(self.map(plane), shape, strides);
})
```

And then one can do something like this in Python:
```
m = fb.map(0)

for y in range(300, 400):
    for x in range(500, 600):
        m[y, x * 4 + 0] = 0x00
        m[y, x * 4 + 1] = 0x00
        m[y, x * 4 + 2] = 0xff
        m[y, x * 4 + 3] = 0x00
```

Although that seems to be quite slow. Possibly there are simpler ways to do the above with core python too.

With numpy, it works fast:

```
import numpy as np

b = np.frombuffer(fb.map(0), dtype=np.uint32).reshape(1200, 1920)

b[300:400, 500:600] = 0xffff00
```

**Comment by Qingwu-Li** [comment]
@tomba Thanks a lot, I modifed according your input！

**Comment by tomba** [comment]
Do you have any test script you can share? How are you using this?

**Comment by tomba** [comment]
Merged, with small changes. Please check that the one I pushed works for you.

Also, it would be great if you have some simple .py tests using this that you can share.

**Comment by Qingwu-Li** [comment]
Here is my test script


```
from PIL import Image
import numpy as np
import pykms


def paint_image_from_path(path: str):
    try:
        card = pykms.Card()
        res = pykms.ResourceManager(card)
        conn = res.reserve_connector()
        crtc = res.reserve_crtc(conn)
        mode = conn.get_default_mode()
        #mode = conn.get_mode("800x600@60.32")
        framebuffer = pykms.DumbFramebuffer(
            card, mode.hdisplay, mode.vdisplay, "XB24")
        crtc.set_mode(conn, framebuffer, mode)
    except Exception as e:
        print(e)
        raise Exception(e)

    image = Image.open(path)
    image = image.resize((mode.hdisplay, mode.vdisplay),
                         Image.Resampling.LANCZOS)
    pixels = np.array(image)
    map = framebuffer.map(0)
    b = np.frombuffer(map, dtype=np.uint8).reshape(600, 800, 4)
    b[:, :, 0:3] = pixels
    input()
```

**Comment by tomba** [comment]
Thanks! I added a simple pic.py test to the repo for this.

**Pull request closed without merging**
