### PR TITLE
Allow compiling with no exceptions

### PR DESCRIPTION
**Pull request by ericcurtin**
So one can build with fno-exceptions

### CODE REVIEW

**Comment by tomba** [comment]
Why do you need this?

**Comment by ericcurtin** [comment]
First of all thanks for creating this library. I'm looking to start a camera in a pre-boot environment, anything that helps keep binary size small or can result in a small performance gain helps, because I am under strict time conditions to get the camera started quickly.

**Comment by tomba** [comment]
Ok. Well, pre-boot env is certainly something I didn't plan this library to be used for =). So do you mean you have full linux running in that env, with DRM drivers? And you're using kms++ to show the frames from the camera on screen?

My initial thoughts about the patch is that it looks like a quick hack to get kms++ compile without exception support. It makes the code messy, and in the no-exceptions case doesn't handle errors correctly. Not that kms++ does a good job of handling errors even now, but still.

I need to do some study to understand how no-exceptions is used elsewhere. I would imagine that projects either choose to use exceptions, or not use them, not both.

And if we go for the minimalist direction, there's the -fno-rtti also...

**Comment by ericcurtin** [comment]
By pre-boot I mean before systemd is complete I guess. Next step is to get it into initrd.

The code was done quickly... But... The code should run the same when exceptions are on.

I suppose that's what these defines are for, projects which support both.

**Pull request closed without merging**
