### PR TITLE
install kmscube

### PR DESCRIPTION
**Pull request by gnidorah**
- add install target for kmscube
~~- install some more utils~~

### CODE REVIEW

**Comment by tomba** [comment]
I have not added those utils to the install targets, as they're just quick hacks. They crash if you give wrong parameters, have hard coded settings, etc.

Is there some particular util you need here? If yes, then I think that util should be cleaned up, and only that one added to the install targets.

**Comment by gnidorah** [comment]
@tomba Ah, I didn't know they are not polished. Could we install kmscube though? It worked fine for me. I would like to use it as a test when bumping your package in NixOS to check it works.

**Comment by tomba** [comment]
kmscube is also not polished, and it's not really testing kms++, but EGL and OpenGL ES. If you just want to check if kms is working, kmstest and kmsprint are much better.

**Comment by gnidorah** [comment]
@tomba Got it! Thank you for explanations!

**Pull request closed without merging**
