### PR TITLE
Optional libdrm omap

### PR DESCRIPTION
**Pull request by matthoosier-garmin**

### CODE REVIEW

**Comment by tomba** [comment]
I'm fine with merging this (after testing it), but isn't autodetection quite common? But I agree that even with autodetection, the user should be able to explicitly enable/disable the feature.

**Comment by matthoosier-garmin** [comment]
> I'm fine with merging this (after testing it), but isn't autodetection quite common? But I agree that even with autodetection, the user should be able to explicitly enable/disable the feature.

Yeah, autodetection is a quite common behavior. There's something of an opinion divide between developers who mainly work on things manually (who want the maximum set of features that their personal customized enables) and packaging maintainers who mainly look for determinism.

I don't think we absolutely have to set the default to 'OFF' (just adding the switch at all suffices), but I'd probably prefer it that way so that the outcome is always predictable.

**Comment by matthoosier-garmin** [comment]
I just realized that this all seems probably like an odd discussion. To set some context: for some reason that's not clear to me, libdrm always builds the OMAP-specific stuff (even when you're not running on an OMAP board). Probably this comes from some sort of idea that if you build libdrm for a distribution like Debian that isn't targeting a specific SOC, then you need all the various hardware backends available.

So even on Linux systems built with Yocto (where you definitely know the specific board on which the software will run), the libdrm-omap stuff is still present in the sysroot of headers/libraries for some totally different system like an i.MX. That's the situation I'd like to prune.

**Comment by tomba** [comment]
Ok, but in that case, shouldn't you rather change libdrm's config, so that it doesn't build libdrm-omap, which then will automatically make kms++ to not build the omap support?

From kms++ point of view, if there is a libdrm-omap present, why wouldn't kms++ automatically enable the omap support? (But even then, nothing wrong with a config option to explicitly disable it).

**Comment by matthoosier-garmin** [comment]
You're right that ideally libdrm would just be built with the --disable-omap option in these cases. 

For whatever reason, this is not the case in the Yocto recipes. Instead, they enable the Omap/Etnaviv/other-special-hardware backends all enabled. The way that libdrm implements those, the runtime symbols for each such hardware-specific backend are held in a different .so file, and these are held in auxiliary packages that are not automatically installed by along with the main libdrm runtime package.

So it's a bit of an odd situation that at compile-time, the full suite of generic and OMAP-specific symbols are present in the sysroot, but the actual runtime packages don't contain the OMAP stuff unless you specifically select it to be installed.

Would it be better to go for auto-enabled, and just plan that the Yocto recipe will explicitly disable the OMAP stuff for now?

**Comment by tomba** [comment]
That does sounds like an issue in the yocto recipes. Enabling libdrm-omap, and making it available when building other components, but then not installing libdrm-omap, is sure to break something.

So I think the current behavior in kms++ is fine. But adding an option to explicitly disable omap support is ok. I think that will solve your issue without any changes to yocto, right?

**Comment by matthoosier-garmin** [comment]
> That does sounds like an issue in the yocto recipes. Enabling libdrm-omap, and making it available when building other components, but then not installing libdrm-omap, is sure to break something.
> 
> So I think the current behavior in kms++ is fine. But adding an option to explicitly disable omap support is ok. I think that will solve your issue without any changes to yocto, right?

Yeah. Maybe as a future improvement we could do something (similar to what libdrm does) to segregate all of the CPU-specific extensions into auxiliary libraries?

**Comment by matthoosier-garmin** [comment]
Does this one seem okay now? I’ve switched it over to keep auto-detecting the omap extensions, with the flag to suppress that requiring explicit usage.

**Pull request merged**
